### ISSUE TITLE
Info on used

### ISSUE THREAD

**Issue by docop** [FascinatedBox/boxdotool#1]
Hi  So i did search a lot for something that can do a keystroke with repeat function. Your : cmd_key.c  look very nice.
 Actually, how can i run it over a ubuntu system ?  it will be in terminal .. or i need to build the code somehow into like an appimage and then run it ?
 Basically, it's to have a key : spacebar press every 20sec.
thanks and happy new year

**Comment by FascinatedBox** [comment]
Oh, hi. I apologize for not answering you sooner since I don't log into github that much (I use it as a mirror of my gitlab work).

This is a command-line tool, and it's my fork of xdotool. You may have some luck downloading xdotool from your distro through apt/rpm/deb/etc..

You can use `xdotool --repeat <# of times> --repeat-delay <20 seconds in ms> key space`. I recommend peeking at `xdotool --help`.

I do not recommend using this tool over xdotool unless you specifically need one of the fixes that I've put in (which I don't think your request covers), or you have a specific bug not addressed promptly by xdotool.

**Comment by docop** [comment]
Oh very cool. thank for the explanation, i get it now. Quite powerfull indeed. And i gues with pre-made script.. it's possible to have it run via a .desktop shortcut too ?
thanks again

**Comment by FascinatedBox** [comment]
> possible to run via desktop shortcut

I believe so, though I haven't tested so I can't say for sure. A tutorial on how to create a desktop file can be found here: https://www.maketecheasier.com/create-desktop-file-linux/

I've had odd experiences with trying to automate key presses through a gui launcher, to the point that I gave up on a couple ideas I had. Hopefully you'll have better luck (since part of my issue was trying to do weird automation stuff).
